name: build

env:
  CONAN_REFERENCE: "zlib/1.2.11"
  CONAN_USERNAME: "conan-burrito"
  CONAN_UPLOAD: "https://conan.yobasoft.de"
  CONAN_STABLE_BRANCH_PATTERN: "release/*"
  CONAN_LOGIN_USERNAME: "${{ secrets.CONAN_LOGIN_USERNAME }}"
  CONAN_PASSWORD: "${{ secrets.CONAN_PASSWORD }}"



on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    name: build-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - name: Install Ninja
        uses: llvm/actions/install-ninja@master
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Checkout profiles
        uses: actions/checkout@v2
        with:
          repository: conan-burrito/profiles
          path: profiles
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            pip install conan conan_package_tools
      - name: Build native
        run:  |
          python .ci/build-default.py
      - name: Build for Android
        if: ! startsWith(matrix.os, 'windows')
        env:
          CONAN_BASE_PROFILE: ${{ github.workspace }}/profiles/android
        run:  |
          python .ci/build-default.py
      - name: Build for Android on Windows
        if: startsWith(matrix.os, 'windows')
        env:
          CONAN_BASE_PROFILE: ${{ github.workspace }}/profiles/android
          CONAN_CMAKE_GENERATOR: Ninja
        run:  |
          python .ci/build-default.py
      - name: Build for iOS
        if: startsWith(matrix.os, 'macos')
        env:
          CONAN_BASE_PROFILE: ${{ github.workspace }}/profiles/ios
        run:  |
          python .ci/build-ios.py

